'use client';
import {useEffect,useState,useRef} from 'react';
import {FileText,Upload,ArrowUpRight,Check,CheckCheck,TriangleAlert,Search,Download,Plus,X,Loader2,Files,ScanLine,ClipboardCheck,ShieldCheck,ChevronRight,RefreshCw,Pencil,Clock,Package,Inbox} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
import {Doc,Fields,issuesFor,money} from '@/lib/documents';
import {demoInvoice,demoPo} from '@/lib/demo';
import './workspace.css';
type Event={action:string;detail:string;created_at:string};
async function request(url:string,options?:RequestInit){const r=await fetch(url,options);const data=await r.json() as {error?:string;documents:Doc[];document:Doc;events:Event[]};if(!r.ok)throw new Error(data.error||'Request failed. Please try again.');return data}
const downloadText=(name:string,text:string)=>{const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
export default function Workspace(){
 const [docs,setDocs]=useState<Doc[]>([]),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [kind,setKind]=useState<'invoice'|'po'>('invoice'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[upload,setUpload]=useState(false),[busy,setBusy]=useState(false),[detailTab,setDetailTab]=useState('review'),[evidence,setEvidence]=useState('');
 const [edit,setEdit]=useState<Fields|null>(null),[note,setNote]=useState(''),[events,setEvents]=useState<Event[]>([]),[auditError,setAuditError]=useState('');
 async function load(preferred?:string){setError('');try{const data=await request('/api/documents');setDocs(data.documents);if(preferred)setSelected(preferred);else setSelected(old=>old||data.documents.find((d:Doc)=>d.kind==='invoice')?.id||'');}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const current=docs.find(d=>d.id===selected),issues=current?issuesFor(current,docs):[],invoices=docs.filter(d=>d.kind==='invoice');
 const status=(d:Doc)=>d.status==='rejected'?'rejected':issuesFor(d,docs).length?'review':d.status==='approved'?'approved':'ready';
 const counts={review:invoices.filter(d=>status(d)==='review').length,ready:invoices.filter(d=>status(d)==='ready').length,approved:invoices.filter(d=>status(d)==='approved').length};
 const visible=docs.filter(d=>d.kind===kind&&(filter==='all'||status(d)===filter)&&[d.fields.number,d.fields.vendor,d.filename].join(' ').toLowerCase().includes(query.toLowerCase()));
 const selectDoc=(id:string)=>{setSelected(id);setDetailTab('review');setNote('');setEvidence('')};
 useEffect(()=>{if(detailTab==='activity'&&selected){setAuditError('');setEvents([]);request('/api/documents/'+selected).then(d=>setEvents(d.events)).catch(e=>setAuditError(e.message))}},[selected,detailTab,docs]);
 async function demo(){setBusy(true);try{await request('/api/demo',{method:'POST'});await load('demo-inv-1042');setKind('invoice');setFilter('all');setQuery('');toast.success('Sample workspace loaded')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function update(statusValue?:Doc['status'],fields?:Fields){if(!current)return;setBusy(true);try{await request('/api/documents/'+current.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:current.revision,status:statusValue,fields,note})});await load();setEdit(null);setNote('');toast.success(fields?'Corrections saved':statusValue==='approved'?'Invoice approved':statusValue==='rejected'?'Document rejected':'Document reopened')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 function badge(d:Doc){const s=status(d);return <span className={'status '+s}>{s==='approved'?<CheckCheck size={13}/>:s==='ready'?<Check size={13}/>:s==='review'?<TriangleAlert size={13}/>:<X size={13}/>}{{review:'Needs review',ready:'Ready to approve',approved:'Approved',rejected:'Rejected'}[s]}</span>}
 function source(value:string){setEvidence(value);setDetailTab('source')}
 return <div className="app-shell"><Toaster position="bottom-right" richColors/>
 <header className="app-header"><a className="brand" href="/"><span className="brand-mark"><ScanLine size={24}/></span><span>DocOps<span className="brand-ai"> AI</span></span></a><div className="header-divider"/><span className="header-label">Document operations</span><div className="header-right"><ShieldCheck size={16}/><span>Private workspace</span><span className="avatar">G</span></div></header>
 <main className="workspace"><div className="breadcrumb">Workspace <ChevronRight size={14}/> Documents</div>
 <div className="page-heading"><div><div className="eyebrow">EXTRACT · MATCH · REVIEW</div><h1>Document workspace</h1><p>Every invoice checked. Every decision traceable.</p></div><div className="heading-actions"><Button variant="outline" disabled={!counts.approved} onClick={()=>{window.location.href='/api/export'}}><Download size={16}/> Export approved</Button><Button onClick={()=>setUpload(true)}><Plus size={17}/> Upload document</Button></div></div>
 <section className="metrics" aria-label="Workspace summary">{[{label:'Invoices received',value:invoices.length,icon:Files,color:'blue',foot:'In this workspace'},{label:'Needs review',value:counts.review,icon:TriangleAlert,color:'amber',foot:'Resolve document exceptions'},{label:'Ready to approve',value:counts.ready,icon:ClipboardCheck,color:'teal',foot:'All matching checks passed'},{label:'Approved invoices',value:counts.approved,icon:CheckCheck,color:'violet',foot:'Available for CSV export'}].map(m=><div className="metric" key={m.label}><div className="metric-top"><span>{m.label}</span><span className={'metric-icon '+m.color}><m.icon size={18}/></span></div><strong>{loading?'—':m.value}</strong><small>{m.foot}</small></div>)}</section>
 {error&&<div role="alert" className="error-banner"><TriangleAlert size={20}/><span>{error}</span><Button variant="outline" size="sm" onClick={()=>load()}>Retry</Button></div>}
 <div className="workspace-grid"><section className="document-list panel"><Tabs value={kind} onValueChange={v=>{setKind(v as 'invoice'|'po');setFilter('all');const first=docs.find(d=>d.kind===v);selectDoc(first?.id||'')}}><div className="list-heading"><TabsList variant="line"><TabsTrigger value="invoice">Invoices <span className="count">{invoices.length}</span></TabsTrigger><TabsTrigger value="po">Purchase orders <span className="count">{docs.filter(d=>d.kind==='po').length}</span></TabsTrigger></TabsList><Button aria-label="Refresh documents" variant="ghost" size="icon" onClick={()=>load()}><RefreshCw size={16}/></Button></div><div className="list-tools"><div className="search-box"><Search size={16}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search vendor or document…" aria-label="Search documents"/></div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="status-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="review">Needs review</SelectItem><SelectItem value="ready">Ready to approve</SelectItem><SelectItem value="approved">Approved</SelectItem><SelectItem value="rejected">Rejected</SelectItem></SelectContent></Select></div>
 <TabsContent value={kind}>{loading?<div className="empty"><Loader2 className="spin"/><p>Loading documents…</p></div>:visible.length?<Table><TableHeader><TableRow><TableHead>Document / vendor</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead className="sr-only">Open</TableHead></TableRow></TableHeader><TableBody>{visible.map(d=><TableRow key={d.id} className={selected===d.id?'selected-row':''} onClick={()=>selectDoc(d.id)}><TableCell><button className="document-link" onClick={()=>selectDoc(d.id)}><span className={'file-icon '+(d.kind==='po'?'po':'')}><FileText size={19}/></span><span><strong>{d.fields.number||d.filename}</strong><small>{d.fields.vendor||'Vendor not found'}</small>{d.id.startsWith('demo-')&&<span className="sample-label">SAMPLE</span>}</span></button></TableCell><TableCell className="amount-cell">{money(d.fields.total,d.fields.currency)}<small>{d.fields.date||'Date not found'}</small></TableCell><TableCell>{badge(d)}</TableCell><TableCell><ChevronRight size={15} className="muted"/></TableCell></TableRow>)}</TableBody></Table>:<div className="empty"><span className="empty-icon"><Inbox size={30}/></span><h2>{docs.length?'No matching documents':'Your first document starts here'}</h2><p>{docs.length?'Try another search or upload a document.':'Upload an invoice and its purchase order, or explore a sample match and mismatch.'}</p><Button onClick={()=>setUpload(true)}><Upload size={16}/> Upload document</Button>{!docs.length&&<button className="text-link" onClick={demo} disabled={busy}>{busy?'Loading…':'Explore sample workspace'} <ArrowUpRight size={15}/></button>}</div>}</TabsContent></Tabs>
 <div className="table-footer"><span>{visible.length} {kind==='invoice'?'invoices':'purchase orders'}</span><span><ShieldCheck size={14}/> Saved to your workspace</span></div></section>
 <aside className="review-panel panel" aria-label="Document review">{current?<><div className="review-heading"><div className="eyebrow">DOCUMENT REVIEW</div><div className="review-title"><h2>{current.fields.number||'Untitled document'}</h2>{badge(current)}</div><p>{current.fields.vendor||current.filename}</p></div><Tabs value={detailTab} onValueChange={setDetailTab}><TabsList variant="line" className="detail-tabs"><TabsTrigger value="review">Review</TabsTrigger><TabsTrigger value="source">Source</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger></TabsList><TabsContent value="review" className="detail-content">
 <div className={'check-banner '+(issues.length?'has-issues':'all-clear')}>{issues.length?<TriangleAlert size={22}/>:<CheckCheck size={22}/>}<div><strong>{issues.length?`${issues.length} check${issues.length===1?'':'s'} need attention`:'All checks passed'}</strong><p>{issues.length?'Compare with the source before approving.':'Review the original, then approve this document.'}</p></div></div>
 <div className="section-heading"><h3>Extracted fields</h3><Button variant="ghost" size="sm" onClick={()=>setEdit(structuredClone(current.fields))}><Pencil size={14}/> Edit</Button></div><dl className="fields-grid">{[['Invoice / PO',current.fields.number],['PO reference',current.fields.poNumber],['Document date',current.fields.date],['Currency',current.fields.currency]].map(([k,v])=><div key={k}><dt>{k}</dt><dd><button onClick={()=>source(v)} title="View source evidence">{v||<span className="missing">Not found</span>}</button></dd></div>)}</dl>
 <div className="line-items"><h3>Line items <span className="count">{current.fields.items.length}</span></h3>{current.fields.items.length?current.fields.items.map((item,i)=><div className="line-item" key={i}><div><button className="item-description" onClick={()=>source(item.description)}>{item.description}</button><small>{item.quantity} × {money(item.unitPrice,current.fields.currency)}</small></div><strong>{money(item.amount,current.fields.currency)}</strong></div>):<p className="muted">Add line items using Edit.</p>}</div>
 <div className="totals"><div><span>Subtotal</span><span>{money(current.fields.subtotal,current.fields.currency)}</span></div><div><span>Tax</span><span>{money(current.fields.tax,current.fields.currency)}</span></div><div className="grand-total"><strong>Total</strong><strong>{money(current.fields.total,current.fields.currency)}</strong></div></div>
 {issues.length>0&&<div className="checks"><h3>Matching checks</h3>{issues.map((issue,i)=><div className="issue" key={i}><TriangleAlert size={15}/><div><strong>{issue.label}</strong><p>{issue.detail}</p></div></div>)}</div>}
 <p className="method"><ScanLine size={14}/>{current.method}</p><div className="review-actions"><label htmlFor="review-note">Review note <span>(required for rejection)</span></label><Textarea id="review-note" value={note} onChange={e=>setNote(e.target.value)} placeholder="Add context for this decision…" maxLength={2000}/><div>{current.status!=='review'?<Button variant="outline" disabled={busy} onClick={()=>update('review')}>Reopen review</Button>:<Button variant="outline" disabled={busy||!note.trim()} onClick={()=>update('rejected')}>Reject</Button>}<Button disabled={busy||issues.length>0||status(current)==='approved'||current.status==='rejected'} onClick={()=>update('approved')}><Check size={16}/>{status(current)==='approved'?'Approved':'Approve'}</Button></div></div>
 </TabsContent><TabsContent value="source" className="detail-content"><div className="section-heading"><h3>Source evidence</h3>{current.fileKey&&<a className="text-link" href={'/api/files/'+current.id} target="_blank" rel="noreferrer">Original <ArrowUpRight size={14}/></a>}</div><p className="source-help">Extracted text with line numbers. Highlighted lines contain the selected value. Always check OCR against the original.</p><div className="source-text">{current.text.split('\n').map((line,i)=><div className={evidence&&line.toLowerCase().includes(evidence.toLowerCase())?'highlight':''} key={i}><span>{i+1}</span><code>{line||' '}</code></div>)}</div><Button variant="outline" className="source-download" onClick={()=>downloadText(current.fields.number+'.txt',current.text)}><Download size={15}/> Download extracted text</Button></TabsContent><TabsContent value="activity" className="detail-content"><h3>Review history</h3><div className="event"><Clock size={16}/><div><strong>Document added</strong><p>{new Date(current.createdAt).toLocaleString()}</p><p>{current.method}</p></div></div>{auditError&&<p role="alert">{auditError}</p>}{events.map((e,i)=><div className="event" key={i}><ClipboardCheck size={16}/><div><strong>{e.action}</strong><p>{e.detail}</p><small>{new Date(e.created_at).toLocaleString()}</small></div></div>)}</TabsContent></Tabs></>:<div className="review-placeholder"><div className="document-stack"><ClipboardCheck size={38}/></div><h2>A clearer view of every invoice</h2><p>Select a document to inspect extracted fields, match its purchase order and record a decision.</p><div className="review-steps"><span><ScanLine size={18}/> Extract fields</span><span><Package size={18}/> Match purchase order</span><span><ShieldCheck size={18}/> Review and approve</span></div></div>}</aside></div>
 <footer className="workspace-footer"><span>DocOps AI <span className="footer-version">WORKING MVP</span></span><span>English OCR · PDFs up to 5 pages · Human-reviewed decisions</span><button className="text-link" onClick={demo} disabled={busy}>Load sample documents <ArrowUpRight size={14}/></button></footer></main>
 <UploadDialog open={upload} onOpenChange={setUpload} defaultKind={kind} onAdded={async(id,k)=>{setKind(k);setFilter('all');setQuery('');await load(id)}}/>
 <Dialog open={!!edit} onOpenChange={v=>{if(!v&&!busy)setEdit(null)}}><DialogContent className="edit-dialog"><DialogHeader><DialogTitle>Correct extracted fields</DialogTitle><DialogDescription>Use the original document as the source. Saving corrections returns the document to review.</DialogDescription></DialogHeader>{edit&&<form onSubmit={e=>{e.preventDefault();void update(undefined,edit)}}><div className="edit-grid">{(['number','vendor','poNumber','date','currency'] as const).map(k=><label key={k}>{{number:'Document number',vendor:'Vendor',poNumber:'PO reference',date:'Date',currency:'Currency (3 letters)'}[k]}<Input value={edit[k]} onChange={e=>setEdit({...edit,[k]:k==='currency'?e.target.value.toUpperCase():e.target.value})}/></label>)}{(['subtotal','tax','total'] as const).map(k=><label key={k}>{k[0].toUpperCase()+k.slice(1)}<Input type="number" min="0" step="0.01" value={edit[k]??''} onChange={e=>setEdit({...edit,[k]:e.target.value===''?null:Number(e.target.value)})}/></label>)}</div><div className="section-heading"><h3>Line items</h3><Button type="button" variant="outline" size="sm" onClick={()=>setEdit({...edit,items:[...edit.items,{description:'',quantity:1,unitPrice:0,amount:0}]})}><Plus size={14}/> Add line</Button></div><div className="edit-items">{edit.items.map((item,i)=><div className="edit-item" key={i}><label>Description<Input required value={item.description} onChange={e=>setEdit({...edit,items:edit.items.map((x,j)=>j===i?{...x,description:e.target.value}:x)})}/></label>{(['quantity','unitPrice','amount'] as const).map(k=><label key={k}>{{quantity:'Qty',unitPrice:'Unit price',amount:'Amount'}[k]}<Input type="number" required min="0" step="0.01" value={item[k]} onChange={e=>setEdit({...edit,items:edit.items.map((x,j)=>j===i?{...x,[k]:Number(e.target.value)}:x)})}/></label>)}<Button type="button" variant="ghost" size="icon" aria-label={'Remove line '+(i+1)} onClick={()=>setEdit({...edit,items:edit.items.filter((_,j)=>j!==i)})}><X size={16}/></Button></div>)}</div><div className="dialog-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setEdit(null)}>Cancel</Button><Button type="submit" disabled={busy}>{busy?<Loader2 size={16} className="spin"/>:<Check size={16}/>} Save corrections</Button></div></form>}</DialogContent></Dialog>
 </div>
}
function UploadDialog({open,onOpenChange,defaultKind,onAdded}:{open:boolean;onOpenChange:(v:boolean)=>void;defaultKind:'invoice'|'po';onAdded:(id:string,kind:'invoice'|'po')=>Promise<void>}){
 const [kind,setKind]=useState<'invoice'|'po'>(defaultKind),[mode,setMode]=useState('file'),[file,setFile]=useState<File|null>(null),[text,setText]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');const ref=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(open){setKind(defaultKind);setError('')}},[open,defaultKind]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{let result={text,method:'Pasted text'};if(mode==='file'){if(!file)throw new Error('Choose a document to upload.');const {readDocument}=await import('@/lib/read-file');result=await readDocument(file,setProgress)}setProgress('Extracting fields and saving…');const form=new FormData();form.set('kind',kind);form.set('text',result.text);form.set('method',result.method);if(mode==='file'&&file)form.set('file',file);const data=await request('/api/documents',{method:'POST',body:form});await onAdded(data.document.id,kind);onOpenChange(false);setText('');setFile(null);toast.success('Document added. Review its extracted fields.')}catch(e){setError((e as Error).message)}finally{setBusy(false);setProgress('')}}
 return <Dialog open={open} onOpenChange={v=>{if(!busy)onOpenChange(v)}}><DialogContent className="upload-dialog"><DialogHeader><div className="dialog-icon"><Upload size={24}/></div><DialogTitle>Add a document</DialogTitle><DialogDescription>Extract fields, compare with a purchase order and review the result.</DialogDescription></DialogHeader><form onSubmit={submit}><label className="form-label">Document type</label><Select value={kind} onValueChange={v=>setKind(v as 'invoice'|'po')} disabled={busy}><SelectTrigger className="full-width"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="invoice">Invoice</SelectItem><SelectItem value="po">Purchase order</SelectItem></SelectContent></Select><Tabs value={mode} onValueChange={v=>{if(!busy)setMode(v)}} className="upload-tabs"><TabsList><TabsTrigger value="file">Upload file</TabsTrigger><TabsTrigger value="text">Paste text</TabsTrigger></TabsList><TabsContent value="file"><input type="file" ref={ref} accept=".pdf,.png,.jpg,.jpeg,.txt" className="sr-only" aria-label="Choose document" disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/><button type="button" className="dropzone" disabled={busy} onClick={()=>ref.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)setFile(e.dataTransfer.files[0]||null)}}>{file?<FileText size={30}/>:<Upload size={30}/>}<strong>{file?file.name:'Choose a file or drop it here'}</strong><span>{file?`${(file.size/1024).toFixed(0)} KB · Click to replace`:'PDF, PNG, JPG or TXT · Up to 10 MB'}</span></button><p className="source-help">English OCR runs in your browser. The original file and extracted text are saved to this private workspace. PDFs: up to 5 pages.</p></TabsContent><TabsContent value="text"><Textarea aria-label="Document text" value={text} onChange={e=>setText(e.target.value)} className="paste-text" maxLength={100000} placeholder={'Invoice: INV-001\nVendor: Your supplier\nPO: PO-001\nDate: 2026-09-09\nCurrency: INR\nDescription | Quantity | Unit price | Amount\nDesk | 2 | 5000 | 10000\nSubtotal: 10000\nTax: 1800\nTotal: 11800'}/><p className="source-help">For line items, separate Description | Quantity | Unit price | Amount with pipes.</p><button type="button" className="text-link" onClick={()=>setText(kind==='invoice'?demoInvoice:demoPo)}>Insert sample text</button></TabsContent></Tabs>{error&&<p className="upload-error" role="alert">{error}</p>}{busy&&<p className="progress-message" role="status"><Loader2 className="spin" size={16}/>{progress}</p>}<div className="dialog-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={busy||(mode==='file'?!file:!text.trim())}>{busy?<Loader2 className="spin" size={16}/>:<ScanLine size={16}/>} Extract & review</Button></div></form></DialogContent></Dialog>
}
